#!/bin/bash

options=("arm7a" "aarch64")
select opt in "${options[@]}"
do
    case $opt in
        "arm7a")
            export HOST=armv7a-linux-androideabi
            break
            ;;
        "aarch64")
            export HOST=aarch64-linux-android
            break
            ;;
        *) echo "invalid option $REPLY";;
    esac
done

export ANDROID_NDK_HOME=~/android-tools/android-ndk-r26d
export HOST_TAG=linux-x86_64
export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/$HOST_TAG
export AR=$TOOLCHAIN/bin/llvm-ar
export AS=$TOOLCHAIN/bin/llvm-as
export CC=$TOOLCHAIN/bin/${HOST}24-clang
export CXX=$TOOLCHAIN/bin/${HOST}24-clang++
export LD=$TOOLCHAIN/bin/ld
export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
export STRIP=$TOOLCHAIN/bin/llvm-strip

rm -R dnsmasq-2.91
wget -nc https://thekelleys.org.uk/dnsmasq/dnsmasq-2.91.tar.gz
tar -xf dnsmasq-2.91.tar.gz
patch -N -p1 < dnsmasq.patch
cd dnsmasq-2.91
make
$STRIP src/dnsmasq
mv src/dnsmasq ../dnsmasq_$HOST
